# SOURCE: https://www.bezkoder.com/docker-compose-react-nodejs-mysql/

version: '3.8' # Docker Compose file format version

services: # individual services in isolated containers
    mysqldb:
      image: mysql:5.7  # official Docker image
      restart: unless-stopped
      env_file: ./.env
      environment:  # provide setting using environment variables
        - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
      ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
      volumes:
        - db:/var/lib/mysql
      networks:
        - backend
    
    api:
      depends_on:
      - mysqldb
      build: ./api
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      environment:  # environment variables that Node application uses
        - DB_HOST=mysqldb
        - DB_USER=$MYSQLDB_USER
        - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - DB_NAME=$MYSQLDB_DATABASE
        - DB_PORT=$MYSQLDB_DOCKER_PORT
        - CLIENT_ORIGIN=$CLIENT_ORIGIN
      networks:
        - backend
        - frontend
    
    client:
      depends_on:
        - api
      build:  # environment variables only accessed during build process
        context: ./client
        args:
          - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
      ports:
        - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
      networks:
        - frontend  

volumes: # named volumes that keep data alive after restart
  db:

networks: # facilitate communication between containers
